package com.gowayki.nesh.app.common.modules.auth

object AuthCopy {
    const val signInTitle = "Iniciar sesión"
    const val signInSubtitle = "Accede para continuar en Nesh"
    const val registerTitle = "Completa tu perfil"
    const val registerSubtitle = "Necesitamos estos datos para activar tu cuenta"
    const val brandTagline = "Operaciones de red de movilidad"
    const val systemName = "Gowayki Nesh"
    const val googleSignIn = "Continuar con Google"
    const val connectingGoogle = "Conectando…"
    const val securityTerms = "Al continuar aceptas las políticas de uso y privacidad."
    const val authFailed = "No se pudo completar el inicio de sesión."
    const val closedByUser = "Inicio de sesión cancelado."
    const val legalNotice = "© 2026 GoWayki"
    const val signedInAs = "Sesión iniciada"
    const val signOut = "Cerrar sesión"
    const val nameLabel = "Nombre completo"
    const val namePlaceholder = "Cómo quieres aparecer"
    const val genderLabel = "Género"
    const val genderMale = "Masculino"
    const val genderFemale = "Femenino"
    const val genderOther = "Otro"
    const val acceptTerms = "Acepto términos y privacidad"
    const val saveAndContinue = "Guardar y entrar"
    const val nameRequired = "El nombre es obligatorio (mín. 2 caracteres)."
    const val termsRequired = "Debes aceptar los términos para continuar."
    const val registrationFailed = "No se pudo guardar el perfil."
    const val accountStatusFailed = "No se pudo verificar tu cuenta."
    const val passwordShow = "Mostrar"
    const val passwordHide = "Ocultar"
}
